x-game-env: &game-env
  WORLD_NAME: ${WORLD_NAME}
  WORLD_UNIQUE_NAME: ${WORLD_UNIQUE_NAME}
  BATTLEGROUP_ID: ${BATTLEGROUP_ID}
  FLS_SECRET: ${FLS_SECRET}
  FLS_SECRET_FILE: /run/secrets/funcom-token.txt
  DUNE_SERVER_LOGIN_PASSWORD: ${DUNE_SERVER_LOGIN_PASSWORD}
  EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS}
  GAME_RMQ_PUBLIC_HOST: ${GAME_RMQ_PUBLIC_HOST}
  GAME_RMQ_PUBLIC_PORT: ${GAME_RMQ_PUBLIC_PORT}
  GAME_RMQ_HOST: 127.0.0.1
  GAME_RMQ_PORT: ${GAME_RMQ_PUBLIC_PORT}
  ADMIN_RMQ_HOST: 127.0.0.1
  ADMIN_RMQ_PORT: "5672"
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: dune
  POSTGRES_USER: dune
  POSTGRES_PASSWORD: ${POSTGRES_DUNE_PASSWORD}
  DATABASE_URL: postgres://dune:${POSTGRES_DUNE_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/dune
  DUNE_CONFIG_DIR: /config

x-game-service-common: &game-service-common
  image: funcom/self-hosting/seabass-server:${DUNE_IMAGE_TAG}
  dns:
    - 1.1.1.1
    - 8.8.8.8
  network_mode: host
  restart: unless-stopped
  depends_on:
    postgres:
      condition: service_healthy
    admin-rmq:
      condition: service_healthy
    game-rmq:
      condition: service_healthy
    db-init:
      condition: service_completed_successfully
  entrypoint:
    - /bin/sh
    - -lc
  command: >-
    exec /workspace/scripts/run_server_safe.sh "$${DUNE_MAP}"
    -ini:engine:[FuncomLiveServices]:ServiceAuthToken=$${FLS_SECRET}
    -ini:engine:[OnlineSubsystem]:ServerName=$${WORLD_UNIQUE_NAME}
    -ini:engine:[ConsoleVariables]:Bgd.ServerLoginPassword=$${DUNE_SERVER_LOGIN_PASSWORD}
    -ExternalAddress=$${EXTERNAL_ADDRESS}
    --RMQGameHostname=$${GAME_RMQ_HOST}
    --RMQGamePort=$${GAME_RMQ_PORT}
    --RMQAdminHostname=$${ADMIN_RMQ_HOST}
    --RMQAdminPort=$${ADMIN_RMQ_PORT}
    -Port=$${DUNE_GAME_PORT}
    -IGWPort=$${DUNE_S2S_PORT}
    -PartitionIndex=$${DUNE_PARTITION_INDEX}

services:
  overmap:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_OVERMAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Systems/Overmap/Overmap.Overmap, DUNE_GAME_PORT: "7777", DUNE_S2S_PORT: "7888", DUNE_PARTITION_INDEX: "1" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/overmap:/home/dune/server/DuneSandbox/Saved]

  survival_1:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7778", DUNE_S2S_PORT: "7889", DUNE_PARTITION_INDEX: "2" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_1:/home/dune/server/DuneSandbox/Saved]

  deep_desert_1:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEEP_DESERT}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/DeepDesert_1/DeepDesert_1.DeepDesert_1, DUNE_GAME_PORT: "7779", DUNE_S2S_PORT: "7890", DUNE_PARTITION_INDEX: "3" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/deep_desert_1:/home/dune/server/DuneSandbox/Saved]

  arrakeen:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/SocialHubs/Arrakeen/SH_Arrakeen.SH_Arrakeen, DUNE_GAME_PORT: "7780", DUNE_S2S_PORT: "7891", DUNE_PARTITION_INDEX: "4" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/arrakeen:/home/dune/server/DuneSandbox/Saved]

  harko_village:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/SocialHubs/HarkoVillage/SH_HarkoVillage.SH_HarkoVillage, DUNE_GAME_PORT: "7781", DUNE_S2S_PORT: "7892", DUNE_PARTITION_INDEX: "5" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/harko_village:/home/dune/server/DuneSandbox/Saved]

  testing_hephaestus:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/WreckOfTheHephaestus/CB_Story_Hephaestus/CB_Story_Hephaestus.CB_Story_Hephaestus, DUNE_GAME_PORT: "7782", DUNE_S2S_PORT: "7893", DUNE_PARTITION_INDEX: "6" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_hephaestus:/home/dune/server/DuneSandbox/Saved]

  testing_carthag:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/BeneathOldCarthag/CB_Story_Ecolab_Carthag/CB_Story_Ecolab_Carthag.CB_Story_Ecolab_Carthag, DUNE_GAME_PORT: "7783", DUNE_S2S_PORT: "7894", DUNE_PARTITION_INDEX: "7" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_carthag:/home/dune/server/DuneSandbox/Saved]

  testing_waterfat:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/WaterFatManor/CB_Story_WaterFatManor.CB_Story_WaterFatManor, DUNE_GAME_PORT: "7784", DUNE_S2S_PORT: "7895", DUNE_PARTITION_INDEX: "8" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_waterfat:/home/dune/server/DuneSandbox/Saved]

  proces_verbal:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/MainStory_Chapter2/ProcesVerbal/ProcesVerbalMap/Story_ProcesVerbal.Story_ProcesVerbal, DUNE_GAME_PORT: "7785", DUNE_S2S_PORT: "7896", DUNE_PARTITION_INDEX: "9" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/proces_verbal:/home/dune/server/DuneSandbox/Saved]

  survival_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7786", DUNE_S2S_PORT: "7897", DUNE_PARTITION_INDEX: "10" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_2:/home/dune/server/DuneSandbox/Saved]

  survival_3:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7787", DUNE_S2S_PORT: "7898", DUNE_PARTITION_INDEX: "11" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_3:/home/dune/server/DuneSandbox/Saved]

  survival_4:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7788", DUNE_S2S_PORT: "7899", DUNE_PARTITION_INDEX: "12" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_4:/home/dune/server/DuneSandbox/Saved]

  survival_5:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7789", DUNE_S2S_PORT: "7900", DUNE_PARTITION_INDEX: "13" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_5:/home/dune/server/DuneSandbox/Saved]

  survival_6:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7790", DUNE_S2S_PORT: "7901", DUNE_PARTITION_INDEX: "14" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_6:/home/dune/server/DuneSandbox/Saved]

  survival_7:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7791", DUNE_S2S_PORT: "7902", DUNE_PARTITION_INDEX: "15" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_7:/home/dune/server/DuneSandbox/Saved]

  survival_8:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7792", DUNE_S2S_PORT: "7903", DUNE_PARTITION_INDEX: "16" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_8:/home/dune/server/DuneSandbox/Saved]

  survival_9:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7793", DUNE_S2S_PORT: "7904", DUNE_PARTITION_INDEX: "17" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_9:/home/dune/server/DuneSandbox/Saved]

  survival_10:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7794", DUNE_S2S_PORT: "7905", DUNE_PARTITION_INDEX: "18" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_10:/home/dune/server/DuneSandbox/Saved]

  survival_11:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7795", DUNE_S2S_PORT: "7906", DUNE_PARTITION_INDEX: "19" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_11:/home/dune/server/DuneSandbox/Saved]

  survival_12:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7796", DUNE_S2S_PORT: "7907", DUNE_PARTITION_INDEX: "20" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_12:/home/dune/server/DuneSandbox/Saved]

  survival_13:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7797", DUNE_S2S_PORT: "7908", DUNE_PARTITION_INDEX: "21" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_13:/home/dune/server/DuneSandbox/Saved]

  survival_14:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7798", DUNE_S2S_PORT: "7909", DUNE_PARTITION_INDEX: "22" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_14:/home/dune/server/DuneSandbox/Saved]

  survival_15:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7799", DUNE_S2S_PORT: "7910", DUNE_PARTITION_INDEX: "23" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_15:/home/dune/server/DuneSandbox/Saved]

  survival_16:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7800", DUNE_S2S_PORT: "7911", DUNE_PARTITION_INDEX: "24" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_16:/home/dune/server/DuneSandbox/Saved]

  survival_17:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_SURVIVAL}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/Survival_1/Survival_1.Survival_1, DUNE_GAME_PORT: "7801", DUNE_S2S_PORT: "7912", DUNE_PARTITION_INDEX: "25" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/survival_17:/home/dune/server/DuneSandbox/Saved]

  deep_desert_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEEP_DESERT}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/DeepDesert_1/DeepDesert_1.DeepDesert_1, DUNE_GAME_PORT: "7802", DUNE_S2S_PORT: "7913", DUNE_PARTITION_INDEX: "26" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/deep_desert_2:/home/dune/server/DuneSandbox/Saved]

  deep_desert_3:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEEP_DESERT}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/DeepDesert_1/DeepDesert_1.DeepDesert_1, DUNE_GAME_PORT: "7803", DUNE_S2S_PORT: "7914", DUNE_PARTITION_INDEX: "27" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/deep_desert_3:/home/dune/server/DuneSandbox/Saved]

  deep_desert_4:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEEP_DESERT}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/DeepDesert_1/DeepDesert_1.DeepDesert_1, DUNE_GAME_PORT: "7804", DUNE_S2S_PORT: "7915", DUNE_PARTITION_INDEX: "28" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/deep_desert_4:/home/dune/server/DuneSandbox/Saved]

  deep_desert_5:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEEP_DESERT}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/Arrakis/DeepDesert_1/DeepDesert_1.DeepDesert_1, DUNE_GAME_PORT: "7805", DUNE_S2S_PORT: "7916", DUNE_PARTITION_INDEX: "29" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/deep_desert_5:/home/dune/server/DuneSandbox/Saved]

  arrakeen_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/SocialHubs/Arrakeen/SH_Arrakeen.SH_Arrakeen, DUNE_GAME_PORT: "7806", DUNE_S2S_PORT: "7917", DUNE_PARTITION_INDEX: "30" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/arrakeen_2:/home/dune/server/DuneSandbox/Saved]

  harko_village_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/SocialHubs/HarkoVillage/SH_HarkoVillage.SH_HarkoVillage, DUNE_GAME_PORT: "7807", DUNE_S2S_PORT: "7918", DUNE_PARTITION_INDEX: "31" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/harko_village_2:/home/dune/server/DuneSandbox/Saved]

  testing_hephaestus_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/WreckOfTheHephaestus/CB_Story_Hephaestus/CB_Story_Hephaestus.CB_Story_Hephaestus, DUNE_GAME_PORT: "7808", DUNE_S2S_PORT: "7919", DUNE_PARTITION_INDEX: "32" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_hephaestus_2:/home/dune/server/DuneSandbox/Saved]

  testing_carthag_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/BeneathOldCarthag/CB_Story_Ecolab_Carthag/CB_Story_Ecolab_Carthag.CB_Story_Ecolab_Carthag, DUNE_GAME_PORT: "7809", DUNE_S2S_PORT: "7920", DUNE_PARTITION_INDEX: "33" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_carthag_2:/home/dune/server/DuneSandbox/Saved]

  testing_waterfat_2:
    <<: *game-service-common
    mem_limit: ${MEM_LIMIT_DEFAULT_MAP}
    environment: { <<: *game-env, DUNE_MAP: /Game/Dune/Maps/OverlandMaps_Story/WaterFatManor/CB_Story_WaterFatManor.CB_Story_WaterFatManor, DUNE_GAME_PORT: "7810", DUNE_S2S_PORT: "7921", DUNE_PARTITION_INDEX: "34" }
    volumes: [./config:/config:ro, ./secrets:/run/secrets:ro, ./scripts:/workspace/scripts:ro, ./data/server-saved/testing_waterfat_2:/home/dune/server/DuneSandbox/Saved]

