/** Generated from characters/page.tsx grant buttons. Edit this file, not the JSX grids. */

export type GrantItemRef = { templateId: string; quantity: number };

export type GrantEntry =
  | { kind: 'item'; templateId: string; quantity: number; label: string }
  | { kind: 'batch'; label: string; items: GrantItemRef[] }
  | { kind: 'solari'; amount: number; label: string }
  | { kind: 'health'; hp: number; label: string };

export interface GrantGroup {
  catId: string;
  banner?: string;
  bannerIcon?: string;
  title: string;
  description?: string;
  columns?: string;
  entries: GrantEntry[];
}

export const GRANT_GROUPS: GrantGroup[] = [
  {
    catId: "quick",
    title: "Quick Grants",
    description: "One-click common items and resources. Granted items are staged in the database and appear after the player relogs (no server restart needed).",
    entries: [
      { kind: 'solari', amount: 1000, label: "+1,000 Solari" },
      { kind: 'solari', amount: 10000, label: "+10,000 Solari" },
      { kind: 'health', hp: 300, label: "300 HP" },
      { kind: 'health', hp: 500, label: "500 HP" },
      { kind: 'item', templateId: "MelangeSpice", quantity: 50, label: "50 Spice Melange" },
    ],
  },
  {
    catId: "combat",
    banner: "Combat & Armor",
    bannerIcon: "⚔️",
    title: "Weapons",
    description: "Melee weapons, ranged weapons, and ammunition.",
    entries: [
      { kind: 'item', templateId: "ScrapMetalKnife", quantity: 1, label: "Scrap Metal Knife" },
      { kind: 'item', templateId: "Kindjal", quantity: 1, label: "Kindjal" },
      { kind: 'item', templateId: "Dirk", quantity: 1, label: "Dirk" },
      { kind: 'item', templateId: "Rapier", quantity: 1, label: "Rapier" },
      { kind: 'item', templateId: "CHOAMSword_0", quantity: 1, label: "Artisan Sword" },
      { kind: 'item', templateId: "ChoamSda1", quantity: 1, label: "Choam Sidearm" },
      { kind: 'item', templateId: "ChoamSda6", quantity: 1, label: "Adept Maula Pistol" },
      { kind: 'item', templateId: "SurveyProbeLauncher", quantity: 1, label: "Survey Probe Launcher" },
      { kind: 'item', templateId: "Ammo", quantity: 1000, label: "1000 Light Darts" },
      { kind: 'item', templateId: "HeavyAmmo", quantity: 1000, label: "1000 Heavy Darts" },
      { kind: 'item', templateId: "RocketAmmo", quantity: 50, label: "50 Rockets" },
      { kind: 'item', templateId: "InfantryRocketAmmo", quantity: 50, label: "50 Missiles" },
      { kind: 'item', templateId: "Napalm", quantity: 50, label: "50 Incendiary Gel" },
      { kind: 'item', templateId: "T3_Tool_SurveyProbeAmmo", quantity: 20, label: "20 Survey Probes" },
    ],
  },
  {
    catId: "tools",
    banner: "Tools & Equipment",
    bannerIcon: "🛠️",
    title: "Tools and Equipment",
    description: "Mining tools, building tools, and utility items.",
    entries: [
      { kind: 'item', templateId: "MiningTool_1h_Standard", quantity: 1, label: "Mining Tool" },
      { kind: 'item', templateId: "Binoculars_1", quantity: 1, label: "Binoculars" },
      { kind: 'item', templateId: "BasicBuildingTool", quantity: 1, label: "Building Drone" },
      { kind: 'item', templateId: "BodyFluidExtractor", quantity: 1, label: "Fluid Extractor" },
      { kind: 'item', templateId: "PowerPack", quantity: 1, label: "Improvised Power Pack" },
      { kind: 'item', templateId: "PowerPack5", quantity: 1, label: "Power Pack Mk1" },
      { kind: 'item', templateId: "PowerPack4", quantity: 1, label: "Power Pack Mk6" },
      { kind: 'item', templateId: "RepairTool", quantity: 1, label: "Repair Tool" },
      { kind: 'item', templateId: "WeldingMaterial", quantity: 20, label: "20 Welding Material" },
      { kind: 'item', templateId: "PowerUnitVeryLight", quantity: 5, label: "5 Light Power Units" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Sandbike (Mk6)",
    description: "Top-tier sandbike parts. Click Full Kit to grant a complete buildable set.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Sandbike Mk6 Kit", items: [{ templateId: "SandbikeChassis_6", quantity: 1 }, { templateId: "SandbikeEngine_6", quantity: 1 }, { templateId: "SandbikeHull_6", quantity: 1 }, { templateId: "SandbikeLocomotion_6", quantity: 1 }, { templateId: "SandbikeGenerator_6", quantity: 1 }, { templateId: "SandbikeBoost_6", quantity: 1 }, { templateId: "SandbikeInventory_2", quantity: 1 }, { templateId: "SandbikeSeat_1", quantity: 1 }] },
      { kind: 'item', templateId: "SandbikeChassis_6", quantity: 1, label: "Chassis Mk6" },
      { kind: 'item', templateId: "SandbikeEngine_6", quantity: 1, label: "Engine Mk6" },
      { kind: 'item', templateId: "SandbikeHull_6", quantity: 1, label: "Hull Mk6" },
      { kind: 'item', templateId: "SandbikeLocomotion_6", quantity: 1, label: "Tread Mk6" },
      { kind: 'item', templateId: "SandbikeGenerator_6", quantity: 1, label: "PSU Mk6" },
      { kind: 'item', templateId: "SandbikeBoost_6", quantity: 1, label: "Booster Mk6" },
      { kind: 'item', templateId: "SandbikeInventory_2", quantity: 1, label: "Inventory Mk2" },
      { kind: 'item', templateId: "SandbikeSeat_1", quantity: 1, label: "Backseat Mk1" },
      { kind: 'item', templateId: "SandbikeScanner_2", quantity: 1, label: "Scanner Mk2" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Buggy (Mk6)",
    description: "Top-tier buggy parts including weapons and mining attachments.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Buggy Mk6 Kit", items: [{ templateId: "BuggyChassis_6", quantity: 1 }, { templateId: "BuggyEngine_6", quantity: 1 }, { templateId: "BuggyHullFront_6", quantity: 1 }, { templateId: "BuggyHullBack_6", quantity: 1 }, { templateId: "BuggyGenerator_6", quantity: 1 }, { templateId: "BuggyLocomotion_6", quantity: 1 }, { templateId: "BuggyBoost_6", quantity: 1 }, { templateId: "BuggyInventory_6", quantity: 1 }] },
      { kind: 'item', templateId: "BuggyChassis_6", quantity: 1, label: "Chassis Mk6" },
      { kind: 'item', templateId: "BuggyEngine_6", quantity: 1, label: "Engine Mk6" },
      { kind: 'item', templateId: "BuggyHullFront_6", quantity: 1, label: "Hull Mk6" },
      { kind: 'item', templateId: "BuggyHullBack_6", quantity: 1, label: "Rear Mk6" },
      { kind: 'item', templateId: "BuggyHullBackExtra_6", quantity: 1, label: "Utility Rear Mk6" },
      { kind: 'item', templateId: "BuggyGenerator_6", quantity: 1, label: "PSU Mk6" },
      { kind: 'item', templateId: "BuggyLocomotion_6", quantity: 1, label: "Tread Mk6" },
      { kind: 'item', templateId: "BuggyBoost_6", quantity: 1, label: "Booster Mk6" },
      { kind: 'item', templateId: "BuggyInventory_6", quantity: 1, label: "Storage Mk6" },
      { kind: 'item', templateId: "BuggyMining_6", quantity: 1, label: "Cutteray Mk6" },
      { kind: 'item', templateId: "BuggyLauncher_6", quantity: 1, label: "Rocket Launcher Mk6" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Sandcrawler (Mk6)",
    description: "Endgame spice-harvesting vehicle. Mk6 is the only tier.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Sandcrawler Kit", items: [{ templateId: "SandcrawlerChassis_6", quantity: 1 }, { templateId: "SandcrawlerEngine_6", quantity: 1 }, { templateId: "SandcrawlerHull_6", quantity: 1 }, { templateId: "SandcrawlerGenerator_6", quantity: 1 }, { templateId: "SandcrawlerLocomotion_6", quantity: 1 }, { templateId: "SandcrawlerSpiceContainer_6", quantity: 1 }, { templateId: "SandcrawlerSpiceHeader_6", quantity: 1 }] },
      { kind: 'item', templateId: "SandcrawlerChassis_6", quantity: 1, label: "Chassis Mk6" },
      { kind: 'item', templateId: "SandcrawlerEngine_6", quantity: 1, label: "Engine Mk6" },
      { kind: 'item', templateId: "SandcrawlerHull_6", quantity: 1, label: "Cabin Mk6" },
      { kind: 'item', templateId: "SandcrawlerGenerator_6", quantity: 1, label: "PSU Mk6" },
      { kind: 'item', templateId: "SandcrawlerLocomotion_6", quantity: 1, label: "Tread Mk6" },
      { kind: 'item', templateId: "SandcrawlerSpiceContainer_6", quantity: 1, label: "Centrifuge Mk6" },
      { kind: 'item', templateId: "SandcrawlerSpiceHeader_6", quantity: 1, label: "Vacuum Mk6" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Scout Ornithopter (Mk6)",
    description: "Light flying vehicle for exploration and Deep Desert travel.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Scout Mk6 Kit", items: [{ templateId: "OrnithopterLightChassis_6", quantity: 1 }, { templateId: "OrnithopterLightEngine_6", quantity: 1 }, { templateId: "OrnithopterLightHullFront_6", quantity: 1 }, { templateId: "OrnithopterLightHullBack_6", quantity: 1 }, { templateId: "OrnithopterLightLocomotion_6", quantity: 1 }, { templateId: "OrnithopterLightGenerator_6", quantity: 1 }, { templateId: "OrnithopterLightBoost_6", quantity: 1 }, { templateId: "OrnithopterLightInventory_4", quantity: 1 }, { templateId: "OrnithopterLightScanner_4", quantity: 1 }] },
      { kind: 'item', templateId: "OrnithopterLightChassis_6", quantity: 1, label: "Chassis Mk6" },
      { kind: 'item', templateId: "OrnithopterLightEngine_6", quantity: 1, label: "Engine Mk6" },
      { kind: 'item', templateId: "OrnithopterLightHullFront_6", quantity: 1, label: "Cockpit Mk6" },
      { kind: 'item', templateId: "OrnithopterLightHullBack_6", quantity: 1, label: "Hull Mk6" },
      { kind: 'item', templateId: "OrnithopterLightLocomotion_6", quantity: 1, label: "Wing Mk6" },
      { kind: 'item', templateId: "OrnithopterLightLocomotion_Unique_Speed_6", quantity: 1, label: "Albatross Wing Mk6" },
      { kind: 'item', templateId: "OrnithopterLightGenerator_6", quantity: 1, label: "Generator Mk6" },
      { kind: 'item', templateId: "OrnithopterLightBoost_6", quantity: 1, label: "Thruster Mk6" },
      { kind: 'item', templateId: "OrnithopterLightInventory_4", quantity: 1, label: "Storage Mk4" },
      { kind: 'item', templateId: "OrnithopterLightScanner_4", quantity: 1, label: "Scan Module" },
      { kind: 'item', templateId: "OrnithopterLightLauncher_6", quantity: 1, label: "Rocket Launcher Mk6" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Assault Ornithopter (Mk6)",
    description: "Heavy combat ornithopter with rocket launchers and large cabin.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Assault Mk6 Kit", items: [{ templateId: "OrnithopterMediumChassis_6", quantity: 1 }, { templateId: "OrnithopterMediumEngine_6", quantity: 1 }, { templateId: "OrnithopterMediumHull_6", quantity: 1 }, { templateId: "OrnithopterMediumHullFront_6", quantity: 1 }, { templateId: "OrnithopterMediumHullBack_6", quantity: 1 }, { templateId: "OrnithopterMediumLocomotion_6", quantity: 1 }, { templateId: "OrnithopterMediumGenerator_6", quantity: 1 }, { templateId: "OrnithopterMediumBoost_6", quantity: 1 }, { templateId: "OrnithopterMediumInventory_5", quantity: 1 }] },
      { kind: 'item', templateId: "OrnithopterMediumChassis_6", quantity: 1, label: "Chassis Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumEngine_6", quantity: 1, label: "Engine Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumHull_6", quantity: 1, label: "Cabin Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumHullFront_6", quantity: 1, label: "Cockpit Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumHullBack_6", quantity: 1, label: "Tail Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumLocomotion_6", quantity: 1, label: "Wing Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumGenerator_6", quantity: 1, label: "Generator Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumBoost_6", quantity: 1, label: "Thruster Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumInventory_5", quantity: 1, label: "Storage Mk5" },
      { kind: 'item', templateId: "OrnithopterMediumLauncher_6", quantity: 1, label: "Rocket Launcher Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumLocomotion_Unique_Strafe_6", quantity: 1, label: "Hummingbird Wing Mk6" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Vehicle Schematics & Other",
    description: "Unique schematics, respawn beacons, etc.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "SandbikeEngine_Unique_Speed_1_Schematic", quantity: 1, label: "Mohandis Engine Schematic" },
      { kind: 'item', templateId: "RespawnBeacon", quantity: 1, label: "Respawn Beacon" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Carrier Ornithopter (Mk6)",
    description: "New transport-class ornithopter shipped with build 1979201.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Carrier Mk6 Kit", items: [{ templateId: "OrnithopterTransportChassis_6", quantity: 1 }, { templateId: "OrnithopterTransportEngine_6", quantity: 1 }, { templateId: "OrnithopterTransportLocomotion_6", quantity: 1 }, { templateId: "OrnithopterTransportBoost_6", quantity: 1 }, { templateId: "OrnithopterTransportGenerator_6", quantity: 1 }, { templateId: "OrnithopterTransportHull_6", quantity: 1 }, { templateId: "OrnithopterTransportHullFront_6", quantity: 1 }, { templateId: "OrnithopterTransportHullBack_6", quantity: 1 }] },
      { kind: 'item', templateId: "OrnithopterTransportChassis_6", quantity: 1, label: "Carrier Chassis Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportEngine_6", quantity: 1, label: "Carrier Engine Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportLocomotion_6", quantity: 1, label: "Carrier Wing Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportBoost_6", quantity: 1, label: "Carrier Thruster Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportGenerator_6", quantity: 1, label: "Carrier Generator Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportHull_6", quantity: 1, label: "Carrier Main Hull Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportHullFront_6", quantity: 1, label: "Carrier Side Hull Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportHullBack_6", quantity: 1, label: "Carrier Tail Hull Mk6" },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Vehicle Mid-Tier Kits (Mk2 - Mk5)",
    description: "Full intermediate-tier kits for testing or quick progression. Click a tier to grant the full set for that vehicle.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Full Sandbike Mk3", items: [{ templateId: "SandbikeChassis_3", quantity: 1 }, { templateId: "SandbikeEngine_3", quantity: 1 }, { templateId: "SandbikeHull_3", quantity: 1 }, { templateId: "SandbikeLocomotion_3", quantity: 1 }, { templateId: "SandbikeGenerator_3", quantity: 1 }, { templateId: "SandbikeBoost_3", quantity: 1 }] },
      { kind: 'batch', label: "Full Sandbike Mk5", items: [{ templateId: "SandbikeChassis_5", quantity: 1 }, { templateId: "SandbikeEngine_5", quantity: 1 }, { templateId: "SandbikeHull_5", quantity: 1 }, { templateId: "SandbikeLocomotion_5", quantity: 1 }, { templateId: "SandbikeGenerator_5", quantity: 1 }, { templateId: "SandbikeBoost_5", quantity: 1 }] },
      { kind: 'batch', label: "Full Buggy Mk3", items: [{ templateId: "BuggyChassis_3", quantity: 1 }, { templateId: "BuggyEngine_3", quantity: 1 }, { templateId: "BuggyHullFront_3", quantity: 1 }, { templateId: "BuggyHullBack_3", quantity: 1 }, { templateId: "BuggyLocomotion_3", quantity: 1 }, { templateId: "BuggyBoost_3", quantity: 1 }, { templateId: "BuggyGenerator_3", quantity: 1 }, { templateId: "BuggyInventory_3", quantity: 1 }] },
      { kind: 'batch', label: "Full Buggy Mk5", items: [{ templateId: "BuggyChassis_5", quantity: 1 }, { templateId: "BuggyEngine_5", quantity: 1 }, { templateId: "BuggyHullFront_5", quantity: 1 }, { templateId: "BuggyHullBack_5", quantity: 1 }, { templateId: "BuggyLocomotion_5", quantity: 1 }, { templateId: "BuggyBoost_5", quantity: 1 }, { templateId: "BuggyGenerator_5", quantity: 1 }, { templateId: "BuggyInventory_5", quantity: 1 }] },
      { kind: 'batch', label: "Full Scout Ornithopter Mk5", items: [{ templateId: "OrnithopterLightChassis_5", quantity: 1 }, { templateId: "OrnithopterLightEngine_5", quantity: 1 }, { templateId: "OrnithopterLightLocomotion_5", quantity: 1 }, { templateId: "OrnithopterLightBoost_5", quantity: 1 }, { templateId: "OrnithopterLightGenerator_5", quantity: 1 }, { templateId: "OrnithopterLightHullFront_5", quantity: 1 }, { templateId: "OrnithopterLightHullBack_5", quantity: 1 }, { templateId: "OrnithopterLightLauncher_5", quantity: 1 }] },
      { kind: 'batch', label: "Full Assault Ornithopter Mk5", items: [{ templateId: "OrnithopterMediumChassis_5", quantity: 1 }, { templateId: "OrnithopterMediumEngine_5", quantity: 1 }, { templateId: "OrnithopterMediumLocomotion_5", quantity: 1 }, { templateId: "OrnithopterMediumBoost_5", quantity: 1 }, { templateId: "OrnithopterMediumGenerator_5", quantity: 1 }, { templateId: "OrnithopterMediumHull_5", quantity: 1 }, { templateId: "OrnithopterMediumHullFront_5", quantity: 1 }, { templateId: "OrnithopterMediumHullBack_5", quantity: 1 }, { templateId: "OrnithopterMediumLauncher_5", quantity: 1 }] },
    ],
  },
  {
    catId: "vehicles",
    banner: "Vehicles (Mk6)",
    bannerIcon: "🚜",
    title: "Unique Vehicle Modules (Mk6)",
    description: "Named, top-tier unique modules with special bonuses.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "SandbikeEngine_Unique_Speed_6", quantity: 1, label: "Mohandis Sandbike Engine Mk6" },
      { kind: 'item', templateId: "SandbikeBoost_Unique_LessHeat_6", quantity: 1, label: "Night Rider Boost Mk6" },
      { kind: 'item', templateId: "BuggyEngine_Unique_Accelerate_06", quantity: 1, label: "Bluddshot Buggy Engine Mk6" },
      { kind: 'item', templateId: "BuggyBoost_Unique_LessHeat_6", quantity: 1, label: "Rattler Boost Mk6" },
      { kind: 'item', templateId: "BuggyMining_Unique_YieldIncrease_06", quantity: 1, label: "Focused Buggy Cutteray Mk6" },
      { kind: 'item', templateId: "BuggyInventory_Unique_Capacity_06", quantity: 1, label: "Bigger Buggy Boot Mk6" },
      { kind: 'item', templateId: "OrnithopterLightBoost_Unique_LessHeat_6", quantity: 1, label: "Stormrider Boost Mk6" },
      { kind: 'item', templateId: "OrnithopterMediumBoost_Unique_LessHeat_6", quantity: 1, label: "Steady Assault Boost Mk6" },
      { kind: 'item', templateId: "OrnithopterTransportLocomotion_Unique_Speed_6", quantity: 1, label: "Roc Carrier Wing" },
      { kind: 'item', templateId: "OrnithopterTransportBoost_Unique_LessHeat_06", quantity: 1, label: "Steady Carrier Boost Mk6" },
      { kind: 'item', templateId: "SandcrawlerEngine_Unique_Speed_06", quantity: 1, label: "Walker Sandcrawler Engine Mk6" },
      { kind: 'item', templateId: "SandcrawlerLocomotion_Unique_WormThreat_06", quantity: 1, label: "Dampened Sandcrawler Treads" },
      { kind: 'item', templateId: "SandcrawlerSpiceContainer_Unique_Capacity_6", quantity: 1, label: "Upgraded Regis Spice Container" },
    ],
  },
  {
    catId: "materials",
    banner: "Materials & Crafting",
    bannerIcon: "📦",
    title: "Raw Materials",
    description: "Crafting resources and metal bars. Stacks auto-cap to 500.",
    entries: [
      { kind: 'item', templateId: "ScrapMetal", quantity: 500, label: "500 Salvaged Metal" },
      { kind: 'item', templateId: "Stone", quantity: 500, label: "500 Stone" },
      { kind: 'item', templateId: "PlantFiber", quantity: 500, label: "500 Plant Fiber" },
      { kind: 'item', templateId: "Oil", quantity: 500, label: "500 Oil" },
      { kind: 'item', templateId: "FlourSand", quantity: 100, label: "100 Flour Sand (Spice Sand)" },
      { kind: 'item', templateId: "SpiceResidue", quantity: 500, label: "500 Spice Residue" },
      { kind: 'item', templateId: "Mouse_Corpse", quantity: 50, label: "50 Mouse Corpse" },
      { kind: 'item', templateId: "WormTooth", quantity: 25, label: "25 Worm Tooth" },
      { kind: 'item', templateId: "Basalt", quantity: 500, label: "500 Basalt Stone" },
      { kind: 'item', templateId: "DolomiteRock", quantity: 500, label: "500 Carbon Ore (Dolomite)" },
      { kind: 'item', templateId: "MagnetiteOre", quantity: 500, label: "500 Iron Ore (Magnetite)" },
      { kind: 'item', templateId: "AzuriteOre", quantity: 500, label: "500 Azurite Ore" },
      { kind: 'item', templateId: "BauxiteOre", quantity: 500, label: "500 Aluminum Ore" },
      { kind: 'item', templateId: "ErythriteCrystal", quantity: 500, label: "500 Erythrite Crystal" },
      { kind: 'item', templateId: "JasmiumCrystal", quantity: 500, label: "500 Jasmium Crystal" },
      { kind: 'item', templateId: "T4MysaTarilComponent1", quantity: 500, label: "500 Diamondine Dust" },
      { kind: 'item', templateId: "T4MysaTarilComponent2", quantity: 500, label: "500 Carbide Scraps" },
      { kind: 'item', templateId: "T5RadiatedCoreComponent", quantity: 500, label: "500 Irradiated Slag" },
      { kind: 'item', templateId: "CopperBar", quantity: 500, label: "500 Copper Bars" },
      { kind: 'item', templateId: "IronBar", quantity: 500, label: "500 Iron Bars" },
      { kind: 'item', templateId: "SteelBar", quantity: 500, label: "500 Steel Ingots" },
      { kind: 'item', templateId: "AluminiumBar", quantity: 500, label: "500 Aluminum Ingots" },
      { kind: 'item', templateId: "DuraluminumRod", quantity: 500, label: "500 Duraluminum Ingots" },
      { kind: 'item', templateId: "CobaltBar", quantity: 500, label: "500 Cobalt Paste" },
      { kind: 'item', templateId: "Silicone", quantity: 500, label: "500 Silicon" },
      { kind: 'item', templateId: "FuelCanister", quantity: 10, label: "10 Small Fuel Cells" },
      { kind: 'item', templateId: "FuelCanister_Medium", quantity: 10, label: "10 Medium Fuel Cells" },
      { kind: 'item', templateId: "FuelCanister_Large", quantity: 10, label: "10 Large Fuel Cells" },
      { kind: 'item', templateId: "SpicedFuelCell", quantity: 10, label: "10 Spice-infused Fuel" },
      { kind: 'item', templateId: "WindTurbineLubricant1", quantity: 500, label: "500 Low-grade Lubricant" },
      { kind: 'item', templateId: "WindTurbineLubricant2", quantity: 500, label: "500 Industrial Lubricant" },
      { kind: 'item', templateId: "WindTrapFilter1", quantity: 100, label: "100 Makeshift Filter" },
      { kind: 'item', templateId: "WindTrapFilter2", quantity: 100, label: "100 Standard Filter" },
      { kind: 'item', templateId: "WindTrapFilter3", quantity: 100, label: "100 Particulate Filter" },
      { kind: 'item', templateId: "WindTrapFilter4", quantity: 100, label: "100 Adv. Particulate Filter" },
      { kind: 'item', templateId: "WeldingMaterial", quantity: 500, label: "500 Welding Wire" },
      { kind: 'item', templateId: "PowerUnitVeryLight", quantity: 10, label: "10 Light Power Units" },
    ],
  },
  {
    catId: "materials",
    banner: "Materials & Crafting",
    bannerIcon: "📦",
    title: "Crafting Components",
    description: "Tier-1 to Tier-6 components used for advanced crafting (servoks, capacitors, machinery, fabrics). All grants use the verified real Unreal IDs - no ghost stacks.",
    entries: [
      { kind: 'item', templateId: "T3MiningGalleryComponent1", quantity: 500, label: "500 Calibrated Servok" },
      { kind: 'item', templateId: "OldImperialComponent1", quantity: 500, label: "500 Advanced Servoks" },
      { kind: 'item', templateId: "D_OldImperialComponent9", quantity: 500, label: "500 Optimized Servoks" },
      { kind: 'item', templateId: "OldImperialComponent2", quantity: 500, label: "500 Particle Capacitor" },
      { kind: 'item', templateId: "T3MiningGalleryComponent2", quantity: 500, label: "500 Ray Amplifier" },
      { kind: 'item', templateId: "T3MarksmanComponent", quantity: 500, label: "500 Range Finder" },
      { kind: 'item', templateId: "T1RusherComponent", quantity: 500, label: "500 Blade Parts" },
      { kind: 'item', templateId: "T1AssaultComponent", quantity: 500, label: "500 Gun Parts" },
      { kind: 'item', templateId: "T1ExplorationComponent", quantity: 500, label: "500 Holtzman Actuator" },
      { kind: 'item', templateId: "T1UniqueComponent", quantity: 500, label: "500 Spice Copper Dust" },
      { kind: 'item', templateId: "T2UniqueComponent", quantity: 500, label: "500 Spice Iron Dust" },
      { kind: 'item', templateId: "T3UniqueComponent", quantity: 500, label: "500 Spice Steel Dust" },
      { kind: 'item', templateId: "T4UniqueComponent", quantity: 500, label: "500 Spice Aluminum Dust" },
      { kind: 'item', templateId: "T5UniqueComponent", quantity: 500, label: "500 Spice Duralumin Dust" },
      { kind: 'item', templateId: "T6UniqueComponent", quantity: 500, label: "500 Spice Plastanium Dust" },
      { kind: 'item', templateId: "T2MachineComponent", quantity: 500, label: "500 Complex Machinery" },
      { kind: 'item', templateId: "T6Machinery", quantity: 500, label: "500 Advanced Machinery" },
      { kind: 'item', templateId: "T2HeavyComponent", quantity: 500, label: "500 Armor Plating" },
      { kind: 'item', templateId: "T4HarkSpiceSiloComponent1", quantity: 500, label: "500 Industrial Pump" },
      { kind: 'item', templateId: "T4HarkSpiceSiloComponent2", quantity: 500, label: "500 Heavy Compressor" },
      { kind: 'item', templateId: "T4HarkSpiceSiloComponent3", quantity: 500, label: "500 Light Compressor" },
      { kind: 'item', templateId: "T4PyonVillageComponent", quantity: 500, label: "500 Insulated Fabric" },
      { kind: 'item', templateId: "T4MaasKharetComponent1", quantity: 500, label: "500 Sandtrout Leathers" },
      { kind: 'item', templateId: "T4MaasKharetComponent2", quantity: 500, label: "500 Stillsuit Tubing" },
      { kind: 'item', templateId: "T5FactionBaseComponent1", quantity: 500, label: "500 Military Power Reg" },
      { kind: 'item', templateId: "T5FactionBaseComponent2", quantity: 500, label: "500 Hydraulic Piston" },
      { kind: 'item', templateId: "T6BalisticWeave", quantity: 500, label: "500 Ballistic Weave" },
      { kind: 'item', templateId: "T6FilteredFabric", quantity: 500, label: "500 Atmos Filter Fabric" },
      { kind: 'item', templateId: "T6HeavyCalliberCompressor", quantity: 500, label: "500 Fluted Heavy Comp." },
      { kind: 'item', templateId: "T6LightCalliberCompressor", quantity: 500, label: "500 Fluted Light Comp." },
      { kind: 'item', templateId: "T6HoltzmanActuator", quantity: 500, label: "500 Improved Holtzman" },
      { kind: 'item', templateId: "T6Watertube", quantity: 500, label: "500 Improved Watertube" },
      { kind: 'item', templateId: "T6IrradiatedCore", quantity: 500, label: "500 Irradiated Core" },
      { kind: 'item', templateId: "T6CarbidePladeParts", quantity: 500, label: "500 Carbide Blade Parts" },
      { kind: 'item', templateId: "T6PlasteelComponent", quantity: 500, label: "500 Plasteel Plate" },
      { kind: 'item', templateId: "FremenComponent1", quantity: 500, label: "500 EMF Generator" },
      { kind: 'item', templateId: "FremenComponent2", quantity: 500, label: "500 Micro-Sandwich Fabric" },
      { kind: 'item', templateId: "GreatHouseComponent1", quantity: 500, label: "500 Plasteel Microflora" },
      { kind: 'item', templateId: "GreatHouseComponent2", quantity: 500, label: "500 Mechanical Parts" },
      { kind: 'item', templateId: "D_GreatHouseComponent12", quantity: 500, label: "500 Adv. Mechanical Parts" },
    ],
  },
  {
    catId: "survival",
    banner: "Survival & Consumables",
    bannerIcon: "🍞",
    title: "Consumables and Survival",
    description: "Healkits, water, blood sacks, spice consumables. All use verified-real Unreal IDs.",
    entries: [
      { kind: 'item', templateId: "healthpack_channeled", quantity: 20, label: "20 Healkits" },
      { kind: 'item', templateId: "Bloodsack_01", quantity: 10, label: "10 Small Blood Sacks" },
      { kind: 'item', templateId: "Bloodsack_03", quantity: 10, label: "10 Large Blood Sacks" },
      { kind: 'item', templateId: "Bloodsack_T6", quantity: 5, label: "5 Massive Blood Sacks" },
      { kind: 'item', templateId: "Literjon", quantity: 5, label: "5 Literjons" },
      { kind: 'item', templateId: "Literjon_T6", quantity: 5, label: "5 Literjon Mk6" },
      { kind: 'item', templateId: "Decajon", quantity: 1, label: "1 Decaliterjon" },
      { kind: 'item', templateId: "AntiRadiationPill", quantity: 20, label: "20 Iodine Pills" },
      { kind: 'item', templateId: "SaphoJuice", quantity: 5, label: "5 Sapho Juice" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Armor Sets",
    description: "Full armor sets (grants all pieces in one click).",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Sandtrout Leathers (Full)", items: [{ templateId: "Combat_Nati_SandtroutLeathers01_Helmet", quantity: 1 }, { templateId: "Combat_Nati_SandtroutLeathers01_Top", quantity: 1 }, { templateId: "Combat_Nati_SandtroutLeathers01_Bottom", quantity: 1 }, { templateId: "Combat_Nati_SandtroutLeathers01_Gloves", quantity: 1 }, { templateId: "Combat_Nati_SandtroutLeathers01_Boots", quantity: 1 }] },
      { kind: 'batch', label: "Scavenger Rags (Full)", items: [{ templateId: "Combat_Nati_ScavengerRags02_Helmet", quantity: 1 }, { templateId: "Combat_Nati_ScavengerRags02_Top", quantity: 1 }, { templateId: "Combat_Nati_ScavengerRags02_Bottom", quantity: 1 }, { templateId: "Combat_Nati_ScavengerRags02_Gloves", quantity: 1 }, { templateId: "Combat_Nati_ScavengerRags02_Boots", quantity: 1 }] },
      { kind: 'item', templateId: "Stillsuit_Unique_Armored_01_Gloves_Schematic", quantity: 1, label: "Unique Stillsuit Schematic" },
      { kind: 'batch', label: "Scavenger Stillsuit (Full)", items: [{ templateId: "Stillsuit_Neut_Leaking01_Mask", quantity: 1 }, { templateId: "Stillsuit_Neut_Leaking01_Top", quantity: 1 }, { templateId: "Stillsuit_Neut_Leaking01_Gloves", quantity: 1 }, { templateId: "Stillsuit_Neut_Leaking01_Boots", quantity: 1 }] },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "CHOAM Faction Gear",
    description: "Heavy and Stillsuit sets from the June 2026 patch. Click Full Set to grant all pieces at once.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Kirab Heavy Set (Full)", items: [{ templateId: "Combat_Choam_Heavy02_Helmet", quantity: 1 }, { templateId: "Combat_Choam_Heavy02_Top", quantity: 1 }, { templateId: "Combat_Choam_Heavy02_Bottom", quantity: 1 }, { templateId: "Combat_Choam_Heavy02_Gloves", quantity: 1 }, { templateId: "Combat_Choam_Heavy02_Boots", quantity: 1 }] },
      { kind: 'batch', label: "Kirab Stillsuit (Full)", items: [{ templateId: "Stillsuit_Choam_02_Mask", quantity: 1 }, { templateId: "Stillsuit_Choam_02_Top", quantity: 1 }, { templateId: "Stillsuit_Choam_02_Gloves", quantity: 1 }, { templateId: "Stillsuit_Choam_02_Boots", quantity: 1 }] },
      { kind: 'batch', label: "Native Stillsuit (Full)", items: [{ templateId: "Stillsuit_Choam_04_Mask", quantity: 1 }, { templateId: "Stillsuit_Choam_04_Top", quantity: 1 }, { templateId: "Stillsuit_Choam_04_Gloves", quantity: 1 }, { templateId: "Stillsuit_Choam_04_Boots", quantity: 1 }] },
      { kind: 'item', templateId: "CHOAMSword", quantity: 1, label: "CHOAM Standard Sword" },
      { kind: 'item', templateId: "ChoamSda3", quantity: 1, label: "CHOAM Standard Maula Pistol" },
      { kind: 'item', templateId: "ChoamCom1", quantity: 1, label: "CHOAM Static Compactor" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Quality of Life Utilities",
    description: "Tools, belts, scanners, and other utilities that are not otherwise easy to obtain.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "BuildingBlueprint_CopyDevice", quantity: 1, label: "Solido Replicator" },
      { kind: 'item', templateId: "Scanner_Base_1", quantity: 1, label: "Resource Scanner" },
      { kind: 'item', templateId: "HighCapacityLiterjon", quantity: 1, label: "Hajra Literjon Mk1" },
      { kind: 'item', templateId: "SuspensorBelt", quantity: 1, label: "Leap Suspensor Belt" },
      { kind: 'item', templateId: "PartialStabilizationBelt", quantity: 1, label: "Planar Suspensor Belt" },
      { kind: 'item', templateId: "HandHeldTorch", quantity: 1, label: "Glowtube" },
      { kind: 'item', templateId: "HoltzmanShieldActiveDrain", quantity: 1, label: "Holtzman Shield Mk2" },
      { kind: 'item', templateId: "HoltzmanShieldActiveDrain2", quantity: 1, label: "Holtzman Shield Mk3" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Unique / Legendary Weapons",
    description: "One-off uniques and house-tier firearms not on the standard ladder.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "DewReaper_Scythe", quantity: 1, label: "Dew Scythe Mk4" },
      { kind: 'item', templateId: "DewReaper_prototype", quantity: 1, label: "Dew Reaper Mk2" },
      { kind: 'item', templateId: "MiningTool_1h_Unique_01", quantity: 1, label: "Sim&apos;s Cutter" },
      { kind: 'item', templateId: "UniqueSword", quantity: 1, label: "Pseudo Pulse-Sword" },
      { kind: 'item', templateId: "UniqueSda_Story_Ari", quantity: 1, label: "Ari&apos;s Pistol" },
      { kind: 'item', templateId: "AtreSmg2", quantity: 1, label: "Disruptor M11 (Atre)" },
      { kind: 'item', templateId: "HarkAr5", quantity: 1, label: "House Karpov 38 (Hark)" },
      { kind: 'item', templateId: "SmugDmr3", quantity: 1, label: "Artisan JABAL Spitdart" },
      { kind: 'item', templateId: "Scattergun_Prototype0", quantity: 1, label: "Artisan GRDA 44" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Weapon Ladders (Mk0 - Mk3)",
    description: "Dirk / Kindjal / Rapier tier progression and house-faction firearms.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "Dirk_0", quantity: 1, label: "House Dirk" },
      { kind: 'item', templateId: "Dirk_1", quantity: 1, label: "Adept Dirk" },
      { kind: 'item', templateId: "Dirk_3", quantity: 1, label: "Regis Dirk" },
      { kind: 'item', templateId: "Kindjal_1", quantity: 1, label: "Artisan Kindjal" },
      { kind: 'item', templateId: "Kindjal_2", quantity: 1, label: "House Kindjal" },
      { kind: 'item', templateId: "Kindjal_3", quantity: 1, label: "Adept Kindjal" },
      { kind: 'item', templateId: "Rapier_0", quantity: 1, label: "Adept Rapier" },
      { kind: 'item', templateId: "Rapier_3", quantity: 1, label: "Regis Rapier" },
      { kind: 'item', templateId: "CHOAMSword_2", quantity: 1, label: "Adept Sword (CHOAM)" },
      { kind: 'item', templateId: "ChoamSda4", quantity: 1, label: "Artisan Maula Pistol" },
      { kind: 'item', templateId: "HarkAr2", quantity: 1, label: "Karpov 38 (Hark)" },
      { kind: 'item', templateId: "HarkAr4", quantity: 1, label: "Artisan Karpov 38" },
      { kind: 'item', templateId: "Scattergun_Prototype", quantity: 1, label: "Standard GRDA 44" },
      { kind: 'item', templateId: "UniqueAr2", quantity: 1, label: "Unique Assault Rifle Mk2" },
      { kind: 'item', templateId: "UniqueSda_Doubleshot_04", quantity: 1, label: "Unique Double-Shot Sidearm" },
      { kind: 'item', templateId: "UniqueSword_04", quantity: 1, label: "Unique Sword Mk4" },
      { kind: 'item', templateId: "UniqueSword_05", quantity: 1, label: "Replica Pulse-Sword Mk5" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Tool Ladders",
    description: "Power packs, blood extractors, welding torches, and other tool tiers.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "PowerPack2", quantity: 1, label: "Power Pack Mk2" },
      { kind: 'item', templateId: "PowerPack6", quantity: 1, label: "Power Pack Mk3" },
      { kind: 'item', templateId: "PowerPack3", quantity: 1, label: "Power Pack Mk4" },
      { kind: 'item', templateId: "PowerPack7", quantity: 1, label: "Power Pack Mk5" },
      { kind: 'item', templateId: "repairtool3", quantity: 1, label: "Welding Torch Mk3" },
      { kind: 'item', templateId: "repairtool5", quantity: 1, label: "Welding Torch Mk5" },
      { kind: 'item', templateId: "BodyFluidExtractor_02", quantity: 1, label: "Blood Extractor Mk2" },
      { kind: 'item', templateId: "BodyFluidExtractor_03", quantity: 1, label: "Blood Extractor Mk4" },
      { kind: 'item', templateId: "BodyFluidExtractor_2h_tier6", quantity: 1, label: "Blood Extractor Mk6" },
      { kind: 'item', templateId: "MiningTool_1h_Light", quantity: 1, label: "Cutteray Mk2" },
      { kind: 'item', templateId: "miningtool_2h_light", quantity: 1, label: "Cutteray Mk5 (2H)" },
      { kind: 'item', templateId: "fullsuspensorbelt", quantity: 1, label: "Full Suspensor Belt" },
      { kind: 'item', templateId: "holtzmanshieldactivedrain3", quantity: 1, label: "Holtzman Shield Mk5" },
      { kind: 'item', templateId: "vehiclebackuptool", quantity: 1, label: "Vehicle Backup Tool" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "CHOAM Light Mk6 Armor",
    description: "Mk6-tier CHOAM light armor; click Full Set for the complete kit.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "CHOAM Light Mk6 (Full)", items: [{ templateId: "combat_choam_light06_helmet", quantity: 1 }, { templateId: "combat_choam_light06_top", quantity: 1 }, { templateId: "combat_choam_light06_bottom", quantity: 1 }, { templateId: "combat_choam_light06_gloves", quantity: 1 }, { templateId: "combat_choam_light06_boots", quantity: 1 }] },
      { kind: 'item', templateId: "combat_choam_light06_helmet", quantity: 1, label: "Helmet" },
      { kind: 'item', templateId: "combat_choam_light06_top", quantity: 1, label: "Chest" },
      { kind: 'item', templateId: "combat_choam_light06_bottom", quantity: 1, label: "Legs" },
      { kind: 'item', templateId: "combat_choam_light06_gloves", quantity: 1, label: "Gloves" },
      { kind: 'item', templateId: "combat_choam_light06_boots", quantity: 1, label: "Boots" },
      { kind: 'item', templateId: "Combat_Choam_Light02_Top", quantity: 1, label: "Kirab Scout Jacket" },
      { kind: 'item', templateId: "Combat_Choam_Light02_Gloves", quantity: 1, label: "Kirab Scout Gloves" },
      { kind: 'item', templateId: "Combat_Choam_Light03_Boots", quantity: 1, label: "Slaver Scout Boots" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Unique Stillsuits (Efficient T4 / Batigh T5)",
    description: "High-tier unique stillsuit variants with efficient water reclamation.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Efficient T4 (Full)", items: [{ templateId: "Stillsuit_Unique_Efficient_04_mask", quantity: 1 }, { templateId: "Stillsuit_Unique_Efficient_04_top", quantity: 1 }, { templateId: "Stillsuit_Unique_Efficient_04_gloves", quantity: 1 }, { templateId: "Stillsuit_Unique_Efficient_04_boots", quantity: 1 }] },
      { kind: 'batch', label: "Batigh T5 (Full)", items: [{ templateId: "stillsuit_unique_efficient_05_mask", quantity: 1 }, { templateId: "stillsuit_unique_efficient_05_top", quantity: 1 }, { templateId: "stillsuit_unique_efficient_05_gloves", quantity: 1 }, { templateId: "stillsuit_unique_efficient_05_boots", quantity: 1 }] },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "More Vehicle Parts (lower tiers)",
    description: "Mid-tier (Mk1-Mk3) ladder pieces for the Buggy and Sandbike.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "BuggyBoost_3", quantity: 1, label: "Buggy Booster Mk3" },
      { kind: 'item', templateId: "BuggyGenerator_3", quantity: 1, label: "Buggy PSU Mk3" },
      { kind: 'item', templateId: "BuggyInventory_3", quantity: 1, label: "Buggy Storage Mk3" },
      { kind: 'item', templateId: "SandbikeHull_1", quantity: 1, label: "Sandbike Hull Mk1" },
      { kind: 'item', templateId: "SandbikeEngine_1", quantity: 1, label: "Sandbike Engine Mk1" },
      { kind: 'item', templateId: "SandbikeEngine_3", quantity: 1, label: "Sandbike Engine Mk3" },
      { kind: 'item', templateId: "SandbikeLocomotion_1", quantity: 1, label: "Sandbike Tread Mk1" },
      { kind: 'item', templateId: "SandbikeBoost_2", quantity: 1, label: "Sandbike Booster Mk2" },
      { kind: 'item', templateId: "SandbikeGenerator_1", quantity: 1, label: "Sandbike PSU Mk1" },
      { kind: 'item', templateId: "SandbikeGenerator_3", quantity: 1, label: "Sandbike PSU Mk3" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "More Consumables",
    description: "Healthpack tiers, blood sacks, and Melange spice food/drink.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "HealthPack_Channeled_2", quantity: 20, label: "20 Healkit Mk2" },
      { kind: 'item', templateId: "HealthPack_Channeled_3", quantity: 20, label: "20 Healkit Mk4" },
      { kind: 'item', templateId: "HealthPack_Channeled_4", quantity: 20, label: "20 Healkit Mk6" },
      { kind: 'item', templateId: "Bloodsack_02", quantity: 5, label: "5 Medium Blood Sack" },
      { kind: 'item', templateId: "SpiceAddictionConsumable_01", quantity: 10, label: "10 Melange Spiced Food" },
      { kind: 'item', templateId: "SpiceAddictionConsumable_02", quantity: 10, label: "10 Melange Spiced Beer" },
    ],
  },
  {
    catId: "apparel",
    banner: "Apparel & Armor Sets",
    bannerIcon: "🛡️",
    title: "Emotes",
    description: "Character animations and gestures.",
    columns: "grid-cols-3 md:grid-cols-6",
    entries: [
      { kind: 'item', templateId: "Emote_Bow_01", quantity: 1, label: "Bow" },
      { kind: 'item', templateId: "Emote_KaitanBow_01", quantity: 1, label: "Kaitan Bow" },
      { kind: 'item', templateId: "Emote_AtreSalute_01", quantity: 1, label: "Atre Salute" },
      { kind: 'item', templateId: "Emote_Clap_01", quantity: 1, label: "Clap" },
      { kind: 'item', templateId: "Emote_Yes_01", quantity: 1, label: "Yes" },
      { kind: 'item', templateId: "Emote_No_01", quantity: 1, label: "No" },
      { kind: 'item', templateId: "Emote_Point_01", quantity: 1, label: "Point" },
      { kind: 'item', templateId: "Emote_Sit_01", quantity: 1, label: "Sit" },
      { kind: 'item', templateId: "Emote_Threaten_01", quantity: 1, label: "Threaten" },
      { kind: 'item', templateId: "Emote_Follow_01", quantity: 1, label: "Follow" },
      { kind: 'item', templateId: "Emote_ShakeOffSand_01", quantity: 1, label: "Shake Sand" },
      { kind: 'item', templateId: "Emote_AdjustStillsuit", quantity: 1, label: "Adjust Suit" },
    ],
  },
  {
    catId: "cosmetics",
    banner: "Cosmetics, Schematics & Custom",
    bannerIcon: "✨",
    title: "Cosmetics and Schematics",
    description: "Social outfits, schematics, and other unique items.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'batch', label: "Maula Cast-Offs (Full)", items: [{ templateId: "Social_Choam_MaulaCastOffs01_Top_Fremkit", quantity: 1 }, { templateId: "Social_Choam_MaulaCastOffs01_Bottom", quantity: 1 }, { templateId: "Social_Choam_MaulaCastOffs01_Gloves", quantity: 1 }, { templateId: "Social_Choam_MaulaCastOffs01_Shoes", quantity: 1 }] },
      { kind: 'item', templateId: "PowerPack_Unique_Regen_01_Schematic", quantity: 1, label: "Regen PowerPack Schematic" },
      { kind: 'item', templateId: "Schematic_UniqueSuspensor", quantity: 1, label: "Suspensor Schematic" },
      { kind: 'item', templateId: "Schematic_UniqueLiterjon", quantity: 1, label: "Unique Literjon Schematic" },
      { kind: 'item', templateId: "ContractItem", quantity: 1, label: "Contract Item" },
    ],
  },
  {
    catId: "live",
    banner: "Seen on this world",
    bannerIcon: "📡",
    title: "New from this world",
    description: "Template IDs seen in live dune.items on daspicebox that were missing from the grant grid. Verified as real inventory rows, not recipe ghosts.",
    columns: "grid-cols-2 md:grid-cols-3",
    entries: [
      { kind: 'item', templateId: "CHOAMSword_3", quantity: 1, label: "Regis CHOAM Sword" },
      { kind: 'item', templateId: "HarkAr7", quantity: 1, label: "Harkonnen AR Mk7" },
      { kind: 'item', templateId: "AtreLMG5", quantity: 1, label: "Atreides LMG Mk5" },
      { kind: 'item', templateId: "RocketLauncher_2", quantity: 1, label: "Rocket Launcher Mk2" },
      { kind: 'item', templateId: "SmugDmr4", quantity: 1, label: "Smuggler DMR Mk4" },
      { kind: 'item', templateId: "SmugDmr5", quantity: 1, label: "Smuggler DMR Mk5" },
      { kind: 'item', templateId: "HoltzmanShieldActiveDrain3", quantity: 1, label: "Holtzman Shield Mk5" },
      { kind: 'item', templateId: "Radiation_Suit_T5", quantity: 1, label: "Radiation Suit T5" },
      { kind: 'item', templateId: "Bloodsack_Unique_Durable_04", quantity: 1, label: "Durable Blood Sack Mk4" },
      { kind: 'item', templateId: "Combat_Choam_Light05_Gloves", quantity: 1, label: "CHOAM Light Gloves Mk5" },
      { kind: 'item', templateId: "Combat_Choam_Light05_Boots", quantity: 1, label: "CHOAM Light Boots Mk5" },
      { kind: 'item', templateId: "healthpack_channeled_2", quantity: 20, label: "20 Healkit Mk2 (live id)" },
    ],
  },
];

export const GRANT_TEMPLATE_IDS: string[] = GRANT_GROUPS.flatMap((group) =>
  group.entries.flatMap((entry) => {
    if (entry.kind === 'item') return [entry.templateId];
    if (entry.kind === 'batch') return entry.items.map((item) => item.templateId);
    return [];
  }),
);
