; Dune Awakening - Engine Settings
; Performance and network tuning

[/Script/Engine.Engine]
NetServerMaxTickRate=60

[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=100000
MaxInternetClientRate=100000

[/Script/InfiniteGameWorlds.IgwNetDriver]
ConnectionTimeout=604800.0
