#!/usr/bin/env bash
# Generate a machine-local Docker Compose CPU pinning overlay.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
init_dune_env "$0"

# shellcheck source=cpu-pin.sh
source "$SCRIPT_DIR/cpu-pin.sh" --library-only

OUTPUT="${1:-$PROJECT_ROOT/docker-compose.cpupin.yml}"

mapfile -t SERVICES < <(compose_services 2>/dev/null || true)
if ((${#SERVICES[@]} == 0)); then
  SERVICES=(survival_1 deep_desert_1 overmap postgres game-rmq admin-rmq dashboard-api dashboard-frontend)
fi

{
  cat <<EOF
# Generated by scripts/generate-cpupin.sh; do not commit.
# CPU sets are host-specific. Re-run this script after changing hardware.
services:
EOF
  for service in "${SERVICES[@]}"; do
    printf '  %s:\n    cpuset: "%s"\n' "$service" "$(cpuset_for "$service")"
  done
} > "$OUTPUT"

printf 'Wrote %s\n' "$OUTPUT"
